/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package EmployeeDatabase;
import java.lang.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import static javafx.scene.input.KeyCode.J;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
public class EmployeeDatabase extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    DefaultTableModel model=new DefaultTableModel();
    public EmployeeDatabase() {
        initComponents();
        conn= EmployeeDatabase.ConnectDb();
       Object col[]={"EmployeeID","Name","Surname","Gender","DOB","Age","Salary"};
       model.setColumnIdentifiers(col);
       jTable1.setModel(model);
       
        
       updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtEmployeeID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtSalary = new javax.swing.JTextField();
        jbtnAddData = new javax.swing.JButton();
        jbtnClearData = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnDeleteData = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Database");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EmployeeID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jTxtEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTxtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "Name", "Surname", "Gender", "DOB", "Age", "Age"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 620, 410));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jTxtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Surname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jTxtSurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSurnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jTxtAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTxtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jTxtSalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTxtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 150, -1));

        jbtnAddData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnAddData.setText("AddData");
        jbtnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 110, -1));

        jbtnClearData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnClearData.setText("Reset");
        jbtnClearData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClearData, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 90, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jbtnDeleteData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDeleteData.setText("DeleteData");
        jbtnDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDeleteData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        jDateChooser.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, 30));

        jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mandar topre\\Desktop\\priroda-pirs-most-re-reka.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static Connection ConnectDb()
    {
        try
        {
            Class.forName("org.sqlite.JDBC");
            Connection conn= DriverManager.getConnection("jdbc:sqlite:Employee.db");
            return conn;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }
    private void jTxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSurnameActionPerformed
   
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"confirm if you want to exit","Employee Database",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit((0));
        }
        
         
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnClearDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearDataActionPerformed
        
        jTxtEmployeeID.setText(null);
        jTxtName.setText(null);
        jTxtSurname.setText(null);
        jRadioButtonMale.setSelected(false);
        jRadioButtonFemale.setSelected(false);
        jDateChooser.setDate(null);
        jTxtAge.setText(null);
        jTxtSalary.setText(null);
    }//GEN-LAST:event_jbtnClearDataActionPerformed

    private void jbtnDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteDataActionPerformed
        String sql="DELETE FROM Employee WHERE EmployeeID=?";
       
       try
       {
           pst= conn.prepareStatement(sql);
           pst.setString(1,jTxtEmployeeID.getText());
           
           pst.execute();
           JOptionPane.showMessageDialog(null,"Data Deleted from system sucessfully");
           rs.close();
           pst.close();
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
            updateTable();
    }//GEN-LAST:event_jbtnDeleteDataActionPerformed
    private String Gender;
    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        Gender="Male";
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        Gender="Female";
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jbtnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddDataActionPerformed

        String sql="INSERT INTO Employee(EmployeeID,Name,Surname,Gender,DOB,Age,Salary)VALUES(?,?,?,?,?,?,?)";

        try
        {
            pst= conn.prepareStatement(sql);
            pst.setString(1,jTxtEmployeeID.getText());
            pst.setString(2,jTxtName.getText());
            pst.setString(3,jTxtSurname.getText());
            pst.setString(4,Gender);
            pst.setString(5,((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText());
            pst.setString(6,jTxtAge.getText());
            pst.setString(7,jTxtSalary.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Added into system succesfully");
            rs.close();
            pst.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        updateTable();
    }//GEN-LAST:event_jbtnAddDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public void updateTable()
    {
        conn=EmployeeDatabase.ConnectDb();
        if(conn!=null)
        {
            String sql="Select EmployeeID,Name,Surname,Gender,DOB,Age,Salary from Employee";
            try
            {
                pst=conn.prepareStatement(sql);
                rs= pst.executeQuery();
                Object[] columnData=new Object[7];
                while (rs.next())
                        {
                            columnData[0]=rs.getString("EmployeeID");
                            columnData[1]=rs.getString("Name");
                            columnData[2]=rs.getString("Surname");
                            columnData[3]=rs.getString("Gender");
                            columnData[4]=rs.getString("DOB");
                            columnData[5]=rs.getString("Age");
                            columnData[6]=rs.getString("Salary");
                            model.addRow(columnData);
                        }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtEmployeeID;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtSalary;
    private javax.swing.JTextField jTxtSurname;
    private javax.swing.JButton jbtnAddData;
    private javax.swing.JButton jbtnClearData;
    private javax.swing.JButton jbtnDeleteData;
    private javax.swing.JButton jbtnExit;
    // End of variables declaration//GEN-END:variables

   

   
   
}
